version: '3.7'

volumes:
    designpatterns-mysql:
        driver: 'local'

networks:
    designpatterns-net:
        driver: 'bridge'

services:
    db:
        container_name: designpatterns-db
        image: mysql:8.0
        volumes:
            - designpatterns-mysql:/var/lib/mysql
        restart: always
        tty: true
        ports:
            - "3000:3306"
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - TZ=America/Sao_Paulo
        networks:
            - designpatterns-net

    webserver:
        container_name: designpatterns-nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/app
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "5000:80"
        restart: always
        depends_on:
            - db
            - app
        tty: true
        networks:
            - designpatterns-net

    app:
        container_name: designpatterns-php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/app
        ports:
            - "9000"
        restart: always
        tty: true
        environment:
            - DOCKER=1
            - DEBUG_MODE=1
            - DB_HOST=db
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
        networks:
            - designpatterns-net

